@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"C:\Program Files\IAR Systems\Embedded Workbench 6.0\common\bin\cspybat" "C:\Program Files\IAR Systems\Embedded Workbench 6.0\8051\bin\8051proc.dll" "C:\Program Files\IAR Systems\Embedded Workbench 6.0\8051\bin\8051sim.dll"  %1 --plugin "C:\Program Files\IAR Systems\Embedded Workbench 6.0\8051\bin\8051bat.dll" --backend -B "--proc_core" "plain" "--proc_code_model" "near" "--proc_nr_virtual_regs" "24" "--proc_extended_stack" "0x00900" "--proc_pdata_bank_reg_addr" "0x8B" "--proc_dptr_nr_of" "2" "--proc_dptr_switch_method" "INC" "--proc_dptr_DPS" "0xB8" "--proc_dptr_visibility" "separate" "--proc_DPL1" "0x88" "--proc_DPH1" "0x91" "--proc_data_model" "large" "-p" "C:\Program Files\IAR Systems\Embedded Workbench 6.0\8051\config\devices\_generic\io8052.ddf" "--proc_driver" "sim" 


